#!/bin/bash

IMAGE_NAME="tts-hf"
CONTAINER_NAME="tts_dev"

docker build -t $IMAGE_NAME .

docker stop $CONTAINER_NAME 2>/dev/null
docker rm $CONTAINER_NAME 2>/dev/null

echo "🚀 Iniciando sistema TTS interactivo..."

docker run -it \
  --name $CONTAINER_NAME \
  -v $(pwd)/output:/app/output \
  $IMAGE_NAME
